// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AccountTransaction } from "./AccountTransaction";

export interface BankAccountView { account_id: string | null, balance: number, written_checks: Array<string>, account_transactions: Array<AccountTransaction>, }