// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BankAccountDepositMoneyCommandData } from "./BankAccountDepositMoneyCommandData";
import type { BankAccountOpenAccountCommandData } from "./BankAccountOpenAccountCommandData";
import type { BankAccountWithdrawMoneyCommandData } from "./BankAccountWithdrawMoneyCommandData";
import type { BankAccountWriteCheckCommandData } from "./BankAccountWriteCheckCommandData";

export type BankAccountCommand = { OpenAccount: BankAccountOpenAccountCommandData } | { DepositMoney: BankAccountDepositMoneyCommandData } | { WithdrawMoney: BankAccountWithdrawMoneyCommandData } | { WriteCheck: BankAccountWriteCheckCommandData };